package com.netbrasoft.gnuob.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2-jbossorg-2 2015-10-23T20:19:37.806+02:00 Generated
 * source version: 3.1.2-jbossorg-2
 * 
 */
@WebServiceClient(name = "ContentWebServiceImplService", wsdlLocation = "http://localhost:8080/gnuob-soap/ContentWebServiceImpl?wsdl",
    targetNamespace = "http://gnuob.netbrasoft.com/")
public class ContentWebServiceImplService extends Service {

  public final static URL WSDL_LOCATION;

  public final static QName SERVICE = new QName("http://gnuob.netbrasoft.com/", "ContentWebServiceImplService");
  public final static QName ContentWebServiceImplPort = new QName("http://gnuob.netbrasoft.com/", "ContentWebServiceImplPort");

  static {
    URL url = null;
    try {
      url = new URL("http://localhost:8080/gnuob-soap/ContentWebServiceImpl?wsdl");
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(ContentWebServiceImplService.class.getName()).log(java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
          "http://localhost:8080/gnuob-soap/ContentWebServiceImpl?wsdl");
    }
    WSDL_LOCATION = url;
  }

  public ContentWebServiceImplService(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public ContentWebServiceImplService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public ContentWebServiceImplService() {
    super(WSDL_LOCATION, SERVICE);
  }

  public ContentWebServiceImplService(WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE, features);
  }

  public ContentWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  public ContentWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   *
   * @return returns ContentWebServiceImpl
   */
  @WebEndpoint(name = "ContentWebServiceImplPort")
  public ContentWebServiceImpl getContentWebServiceImplPort() {
    return super.getPort(ContentWebServiceImplPort, ContentWebServiceImpl.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns ContentWebServiceImpl
   */
  @WebEndpoint(name = "ContentWebServiceImplPort")
  public ContentWebServiceImpl getContentWebServiceImplPort(WebServiceFeature... features) {
    return super.getPort(ContentWebServiceImplPort, ContentWebServiceImpl.class, features);
  }

}
