package com.netbrasoft.gnuob.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.2-jbossorg-2 2015-11-08T14:18:44.674+01:00 Generated
 * source version: 3.1.2-jbossorg-2
 *
 */
@WebService(targetNamespace = "http://gnuob.netbrasoft.com/", name = "ContentWebServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ContentWebServiceImpl {

  @WebMethod
  @WebResult(name = "countContentResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
  public CountContentResponse countContent(@WebParam(partName = "parameters", name = "countContent", targetNamespace = "http://gnuob.netbrasoft.com/") CountContent parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

  @WebMethod
  @WebResult(name = "findContentResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
  public FindContentResponse findContent(@WebParam(partName = "parameters", name = "findContent", targetNamespace = "http://gnuob.netbrasoft.com/") FindContent parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

  @WebMethod
  @WebResult(name = "findContentByIdResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
  public FindContentByIdResponse findContentById(
      @WebParam(partName = "parameters", name = "findContentById", targetNamespace = "http://gnuob.netbrasoft.com/") FindContentById parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

  @WebMethod
  @WebResult(name = "mergeContentResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
  public MergeContentResponse mergeContent(@WebParam(partName = "parameters", name = "mergeContent", targetNamespace = "http://gnuob.netbrasoft.com/") MergeContent parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

  @WebMethod
  @WebResult(name = "persistContentResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
  public PersistContentResponse persistContent(
      @WebParam(partName = "parameters", name = "persistContent", targetNamespace = "http://gnuob.netbrasoft.com/") PersistContent parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

  @WebMethod
  @WebResult(name = "refreshContentResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
  public RefreshContentResponse refreshContent(
      @WebParam(partName = "parameters", name = "refreshContent", targetNamespace = "http://gnuob.netbrasoft.com/") RefreshContent parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

  @WebMethod
  @WebResult(name = "removeContentResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "result")
  public RemoveContentResponse removeContent(@WebParam(partName = "parameters", name = "removeContent", targetNamespace = "http://gnuob.netbrasoft.com/") RemoveContent parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);
}
