package com.netbrasoft.gnuob.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.5 2015-09-22T18:42:45.744+02:00
 * Generated source version: 3.0.5
 * 
 */
@WebService(targetNamespace = "http://gnuob.netbrasoft.com/", name = "GroupWebServiceImpl")
@XmlSeeAlso({ ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GroupWebServiceImpl {

   @WebResult(name = "findGroupResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
   @WebMethod
   public FindGroupResponse findGroup(@WebParam(partName = "parameters", name = "findGroup", targetNamespace = "http://gnuob.netbrasoft.com/") FindGroup parameters,
         @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

   @WebResult(name = "refreshGroupResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
   @WebMethod
   public RefreshGroupResponse refreshGroup(@WebParam(partName = "parameters", name = "refreshGroup", targetNamespace = "http://gnuob.netbrasoft.com/") RefreshGroup parameters,
         @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

   @WebResult(name = "mergeGroupResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
   @WebMethod
   public MergeGroupResponse mergeGroup(@WebParam(partName = "parameters", name = "mergeGroup", targetNamespace = "http://gnuob.netbrasoft.com/") MergeGroup parameters,
         @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

   @WebResult(name = "persistGroupResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
   @WebMethod
   public PersistGroupResponse persistGroup(@WebParam(partName = "parameters", name = "persistGroup", targetNamespace = "http://gnuob.netbrasoft.com/") PersistGroup parameters,
         @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

   @WebResult(name = "removeGroupResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "result")
   @WebMethod
   public RemoveGroupResponse removeGroup(@WebParam(partName = "parameters", name = "removeGroup", targetNamespace = "http://gnuob.netbrasoft.com/") RemoveGroup parameters,
         @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

   @WebResult(name = "findGroupByIdResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
   @WebMethod
   public FindGroupByIdResponse findGroupById(@WebParam(partName = "parameters", name = "findGroupById", targetNamespace = "http://gnuob.netbrasoft.com/") FindGroupById parameters,
         @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

   @WebResult(name = "countGroupResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
   @WebMethod
   public CountGroupResponse countGroup(@WebParam(partName = "parameters", name = "countGroup", targetNamespace = "http://gnuob.netbrasoft.com/") CountGroup parameters,
         @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);
}
