package com.netbrasoft.gnuob.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.2-jbossorg-2 2015-11-08T14:18:38.946+01:00 Generated
 * source version: 3.1.2-jbossorg-2
 *
 */
@WebService(targetNamespace = "http://gnuob.netbrasoft.com/", name = "GroupWebServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GroupWebServiceImpl {

  @WebMethod
  @WebResult(name = "countGroupResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
  public CountGroupResponse countGroup(@WebParam(partName = "parameters", name = "countGroup", targetNamespace = "http://gnuob.netbrasoft.com/") CountGroup parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

  @WebMethod
  @WebResult(name = "findGroupResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
  public FindGroupResponse findGroup(@WebParam(partName = "parameters", name = "findGroup", targetNamespace = "http://gnuob.netbrasoft.com/") FindGroup parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

  @WebMethod
  @WebResult(name = "findGroupByIdResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
  public FindGroupByIdResponse findGroupById(@WebParam(partName = "parameters", name = "findGroupById", targetNamespace = "http://gnuob.netbrasoft.com/") FindGroupById parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

  @WebMethod
  @WebResult(name = "mergeGroupResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
  public MergeGroupResponse mergeGroup(@WebParam(partName = "parameters", name = "mergeGroup", targetNamespace = "http://gnuob.netbrasoft.com/") MergeGroup parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

  @WebMethod
  @WebResult(name = "persistGroupResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
  public PersistGroupResponse persistGroup(@WebParam(partName = "parameters", name = "persistGroup", targetNamespace = "http://gnuob.netbrasoft.com/") PersistGroup parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

  @WebMethod
  @WebResult(name = "refreshGroupResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
  public RefreshGroupResponse refreshGroup(@WebParam(partName = "parameters", name = "refreshGroup", targetNamespace = "http://gnuob.netbrasoft.com/") RefreshGroup parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

  @WebMethod
  @WebResult(name = "removeGroupResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "result")
  public RemoveGroupResponse removeGroup(@WebParam(partName = "parameters", name = "removeGroup", targetNamespace = "http://gnuob.netbrasoft.com/") RemoveGroup parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);
}
