package com.netbrasoft.gnuob.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-08-11T16:01:38.085+02:00
 * Generated source version: 3.0.5
 * 
 */
@WebService(targetNamespace = "http://gnuob.netbrasoft.com/", name = "OfferWebServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OfferWebServiceImpl {

    @WebMethod
    @WebResult(name = "removeOfferResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "result")
    public RemoveOfferResponse removeOffer(
        @WebParam(partName = "parameters", name = "removeOffer", targetNamespace = "http://gnuob.netbrasoft.com/")
        RemoveOffer parameters,
        @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true)
        MetaData metaData
    );

    @WebMethod
    @WebResult(name = "persistOfferResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
    public PersistOfferResponse persistOffer(
        @WebParam(partName = "parameters", name = "persistOffer", targetNamespace = "http://gnuob.netbrasoft.com/")
        PersistOffer parameters,
        @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true)
        MetaData metaData
    );

    @WebMethod
    @WebResult(name = "findOfferByIdResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
    public FindOfferByIdResponse findOfferById(
        @WebParam(partName = "parameters", name = "findOfferById", targetNamespace = "http://gnuob.netbrasoft.com/")
        FindOfferById parameters,
        @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true)
        MetaData metaData
    );

    @WebMethod
    @WebResult(name = "refreshOfferResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
    public RefreshOfferResponse refreshOffer(
        @WebParam(partName = "parameters", name = "refreshOffer", targetNamespace = "http://gnuob.netbrasoft.com/")
        RefreshOffer parameters,
        @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true)
        MetaData metaData
    );

    @WebMethod
    @WebResult(name = "countOfferResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
    public CountOfferResponse countOffer(
        @WebParam(partName = "parameters", name = "countOffer", targetNamespace = "http://gnuob.netbrasoft.com/")
        CountOffer parameters,
        @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true)
        MetaData metaData
    );

    @WebMethod
    @WebResult(name = "findOfferResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
    public FindOfferResponse findOffer(
        @WebParam(partName = "parameters", name = "findOffer", targetNamespace = "http://gnuob.netbrasoft.com/")
        FindOffer parameters,
        @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true)
        MetaData metaData
    );

    @WebMethod
    @WebResult(name = "mergeOfferResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
    public MergeOfferResponse mergeOffer(
        @WebParam(partName = "parameters", name = "mergeOffer", targetNamespace = "http://gnuob.netbrasoft.com/")
        MergeOffer parameters,
        @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true)
        MetaData metaData
    );
}
