package com.netbrasoft.gnuob.api;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.2-jbossorg-2 2015-11-08T14:18:20.553+01:00 Generated
 * source version: 3.1.2-jbossorg-2
 *
 */
@WebServiceClient(name = "OrderWebServiceImplService", wsdlLocation = "http://localhost:8080/gnuob-soap/OrderWebServiceImpl?wsdl", targetNamespace = "http://gnuob.netbrasoft.com/")
public class OrderWebServiceImplService extends Service {

  public final static URL WSDL_LOCATION;

  public final static QName SERVICE = new QName("http://gnuob.netbrasoft.com/", "OrderWebServiceImplService");
  public final static QName OrderWebServiceImplPort = new QName("http://gnuob.netbrasoft.com/", "OrderWebServiceImplPort");

  static {
    URL url = null;
    try {
      url = new URL("http://localhost:8080/gnuob-soap/OrderWebServiceImpl?wsdl");
    } catch (final MalformedURLException e) {
      java.util.logging.Logger.getLogger(OrderWebServiceImplService.class.getName()).log(java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
          "http://localhost:8080/gnuob-soap/OrderWebServiceImpl?wsdl");
    }
    WSDL_LOCATION = url;
  }

  public OrderWebServiceImplService() {
    super(WSDL_LOCATION, SERVICE);
  }

  public OrderWebServiceImplService(final URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public OrderWebServiceImplService(final URL wsdlLocation, final QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public OrderWebServiceImplService(final URL wsdlLocation, final QName serviceName, final WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  public OrderWebServiceImplService(final URL wsdlLocation, final WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  public OrderWebServiceImplService(final WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE, features);
  }



  /**
   *
   * @return returns OrderWebServiceImpl
   */
  @WebEndpoint(name = "OrderWebServiceImplPort")
  public OrderWebServiceImpl getOrderWebServiceImplPort() {
    return super.getPort(OrderWebServiceImplPort, OrderWebServiceImpl.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns OrderWebServiceImpl
   */
  @WebEndpoint(name = "OrderWebServiceImplPort")
  public OrderWebServiceImpl getOrderWebServiceImplPort(final WebServiceFeature... features) {
    return super.getPort(OrderWebServiceImplPort, OrderWebServiceImpl.class, features);
  }

}
