package com.netbrasoft.gnuob.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.2-jbossorg-2 2015-11-08T14:18:46.625+01:00 Generated
 * source version: 3.1.2-jbossorg-2
 *
 */
@WebService(targetNamespace = "http://gnuob.netbrasoft.com/", name = "PostalCodeWebServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PostalCodeWebServiceImpl {

  @WebMethod
  @WebResult(name = "countPostalCodeResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
  public CountPostalCodeResponse countPostalCode(
      @WebParam(partName = "parameters", name = "countPostalCode", targetNamespace = "http://gnuob.netbrasoft.com/") CountPostalCode parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

  @WebMethod
  @WebResult(name = "findPostalCodeResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
  public FindPostalCodeResponse findPostalCode(
      @WebParam(partName = "parameters", name = "findPostalCode", targetNamespace = "http://gnuob.netbrasoft.com/") FindPostalCode parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

  @WebMethod
  @WebResult(name = "findPostalCodeByIdResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
  public FindPostalCodeByIdResponse findPostalCodeById(
      @WebParam(partName = "parameters", name = "findPostalCodeById", targetNamespace = "http://gnuob.netbrasoft.com/") FindPostalCodeById parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

  @WebMethod
  @WebResult(name = "mergePostalCodeResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
  public MergePostalCodeResponse mergePostalCode(
      @WebParam(partName = "parameters", name = "mergePostalCode", targetNamespace = "http://gnuob.netbrasoft.com/") MergePostalCode parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

  @WebMethod
  @WebResult(name = "persistPostalCodeResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
  public PersistPostalCodeResponse persistPostalCode(
      @WebParam(partName = "parameters", name = "persistPostalCode", targetNamespace = "http://gnuob.netbrasoft.com/") PersistPostalCode parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

  @WebMethod
  @WebResult(name = "refreshPostalCodeResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "parameters")
  public RefreshPostalCodeResponse refreshPostalCode(
      @WebParam(partName = "parameters", name = "refreshPostalCode", targetNamespace = "http://gnuob.netbrasoft.com/") RefreshPostalCode parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);

  @WebMethod
  @WebResult(name = "removePostalCodeResponse", targetNamespace = "http://gnuob.netbrasoft.com/", partName = "result")
  public RemovePostalCodeResponse removePostalCode(
      @WebParam(partName = "parameters", name = "removePostalCode", targetNamespace = "http://gnuob.netbrasoft.com/") RemovePostalCode parameters,
      @WebParam(partName = "metaData", name = "metaData", targetNamespace = "http://gnuob.netbrasoft.com/", header = true) MetaData metaData);
}
