package com.netbrasoft.gnuob.api;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.2-jbossorg-2 2015-11-08T14:18:46.669+01:00 Generated
 * source version: 3.1.2-jbossorg-2
 *
 */
@WebServiceClient(name = "PostalCodeWebServiceImplService", wsdlLocation = "http://localhost:8080/gnuob-soap/PostalCodeWebServiceImpl?wsdl",
    targetNamespace = "http://gnuob.netbrasoft.com/")
public class PostalCodeWebServiceImplService extends Service {

  public final static URL WSDL_LOCATION;

  public final static QName SERVICE = new QName("http://gnuob.netbrasoft.com/", "PostalCodeWebServiceImplService");
  public final static QName PostalCodeWebServiceImplPort = new QName("http://gnuob.netbrasoft.com/", "PostalCodeWebServiceImplPort");

  static {
    URL url = null;
    try {
      url = new URL("http://localhost:8080/gnuob-soap/PostalCodeWebServiceImpl?wsdl");
    } catch (final MalformedURLException e) {
      java.util.logging.Logger.getLogger(PostalCodeWebServiceImplService.class.getName()).log(java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
          "http://localhost:8080/gnuob-soap/PostalCodeWebServiceImpl?wsdl");
    }
    WSDL_LOCATION = url;
  }

  public PostalCodeWebServiceImplService() {
    super(WSDL_LOCATION, SERVICE);
  }

  public PostalCodeWebServiceImplService(final URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public PostalCodeWebServiceImplService(final URL wsdlLocation, final QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public PostalCodeWebServiceImplService(final URL wsdlLocation, final QName serviceName, final WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  public PostalCodeWebServiceImplService(final URL wsdlLocation, final WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  public PostalCodeWebServiceImplService(final WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE, features);
  }



  /**
   *
   * @return returns PostalCodeWebServiceImpl
   */
  @WebEndpoint(name = "PostalCodeWebServiceImplPort")
  public PostalCodeWebServiceImpl getPostalCodeWebServiceImplPort() {
    return super.getPort(PostalCodeWebServiceImplPort, PostalCodeWebServiceImpl.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns PostalCodeWebServiceImpl
   */
  @WebEndpoint(name = "PostalCodeWebServiceImplPort")
  public PostalCodeWebServiceImpl getPostalCodeWebServiceImplPort(final WebServiceFeature... features) {
    return super.getPort(PostalCodeWebServiceImplPort, PostalCodeWebServiceImpl.class, features);
  }

}
