package com.netbrasoft.gnuob.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2-jbossorg-2 2015-10-23T20:19:05.596+02:00 Generated
 * source version: 3.1.2-jbossorg-2
 * 
 */
@WebServiceClient(name = "ProductWebServiceImplService", wsdlLocation = "http://localhost:8080/gnuob-soap/ProductWebServiceImpl?wsdl",
    targetNamespace = "http://gnuob.netbrasoft.com/")
public class ProductWebServiceImplService extends Service {

  public final static URL WSDL_LOCATION;

  public final static QName SERVICE = new QName("http://gnuob.netbrasoft.com/", "ProductWebServiceImplService");
  public final static QName ProductWebServiceImplPort = new QName("http://gnuob.netbrasoft.com/", "ProductWebServiceImplPort");

  static {
    URL url = null;
    try {
      url = new URL("http://localhost:8080/gnuob-soap/ProductWebServiceImpl?wsdl");
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(ProductWebServiceImplService.class.getName()).log(java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
          "http://localhost:8080/gnuob-soap/ProductWebServiceImpl?wsdl");
    }
    WSDL_LOCATION = url;
  }

  public ProductWebServiceImplService(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public ProductWebServiceImplService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public ProductWebServiceImplService() {
    super(WSDL_LOCATION, SERVICE);
  }

  public ProductWebServiceImplService(WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE, features);
  }

  public ProductWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  public ProductWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   *
   * @return returns ProductWebServiceImpl
   */
  @WebEndpoint(name = "ProductWebServiceImplPort")
  public ProductWebServiceImpl getProductWebServiceImplPort() {
    return super.getPort(ProductWebServiceImplPort, ProductWebServiceImpl.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns ProductWebServiceImpl
   */
  @WebEndpoint(name = "ProductWebServiceImplPort")
  public ProductWebServiceImpl getProductWebServiceImplPort(WebServiceFeature... features) {
    return super.getPort(ProductWebServiceImplPort, ProductWebServiceImpl.class, features);
  }

}
