package com.netbrasoft.gnuob.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2-jbossorg-2 2015-10-23T20:19:25.614+02:00 Generated
 * source version: 3.1.2-jbossorg-2
 * 
 */
@WebServiceClient(name = "UserWebServiceImplService", wsdlLocation = "http://localhost:8080/gnuob-soap/UserWebServiceImpl?wsdl",
    targetNamespace = "http://gnuob.netbrasoft.com/")
public class UserWebServiceImplService extends Service {

  public final static URL WSDL_LOCATION;

  public final static QName SERVICE = new QName("http://gnuob.netbrasoft.com/", "UserWebServiceImplService");
  public final static QName UserWebServiceImplPort = new QName("http://gnuob.netbrasoft.com/", "UserWebServiceImplPort");

  static {
    URL url = null;
    try {
      url = new URL("http://localhost:8080/gnuob-soap/UserWebServiceImpl?wsdl");
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(UserWebServiceImplService.class.getName()).log(java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
          "http://localhost:8080/gnuob-soap/UserWebServiceImpl?wsdl");
    }
    WSDL_LOCATION = url;
  }

  public UserWebServiceImplService(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public UserWebServiceImplService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public UserWebServiceImplService() {
    super(WSDL_LOCATION, SERVICE);
  }

  public UserWebServiceImplService(WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE, features);
  }

  public UserWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  public UserWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   *
   * @return returns UserWebServiceImpl
   */
  @WebEndpoint(name = "UserWebServiceImplPort")
  public UserWebServiceImpl getUserWebServiceImplPort() {
    return super.getPort(UserWebServiceImplPort, UserWebServiceImpl.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns UserWebServiceImpl
   */
  @WebEndpoint(name = "UserWebServiceImplPort")
  public UserWebServiceImpl getUserWebServiceImplPort(WebServiceFeature... features) {
    return super.getPort(UserWebServiceImplPort, UserWebServiceImpl.class, features);
  }

}
