#!/bin/sh
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -b gnuob-order-service-binding.xml -k -p com.netbrasoft.gnuob.api -s /home/bernard/Projects/gnuob/gnuob-api/src/main/java -n http://localhost:8080/gnuob-soap/OrderWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -b gnuob-product-service-binding.xml -k -p com.netbrasoft.gnuob.api -s /home/bernard/Projects/gnuob/gnuob-api/src/main/java -n http://localhost:8080/gnuob-soap/ProductWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -b gnuob-paypal-service-binding.xml -k -p com.netbrasoft.gnuob.api -s /home/bernard/Projects/gnuob/gnuob-api/src/main/java -n http://localhost:8080/gnuob-soap/PayPalExpressCheckOutWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -b gnuob-pagseguro-service-binding.xml -k -p com.netbrasoft.gnuob.api -s /home/bernard/Projects/gnuob/gnuob-api/src/main/java -n http://localhost:8080/gnuob-soap/PagseguroCheckOutWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -b gnuob-category-service-binding.xml -k -p com.netbrasoft.gnuob.api -s /home/bernard/Projects/gnuob/gnuob-api/src/main/java -n http://localhost:8080/gnuob-soap/CategoryWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -b gnuob-content-service-binding.xml -k -p com.netbrasoft.gnuob.api -s /home/bernard/Projects/gnuob/gnuob-api/src/main/java -n http://localhost:8080/gnuob-soap/ContentWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -b gnuob-contract-service-binding.xml -k -p com.netbrasoft.gnuob.api -s /home/bernard/Projects/gnuob/gnuob-api/src/main/java -n http://localhost:8080/gnuob-soap/ContractWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -b gnuob-customer-service-binding.xml -k -p com.netbrasoft.gnuob.api -s /home/bernard/Projects/gnuob/gnuob-api/src/main/java -n http://localhost:8080/gnuob-soap/CustomerWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -b gnuob-offer-service-binding.xml -k -p com.netbrasoft.gnuob.api -s /home/bernard/Projects/gnuob/gnuob-api/src/main/java -n http://localhost:8080/gnuob-soap/OfferWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -b gnuob-user-service-binding.xml -k -p com.netbrasoft.gnuob.api -s /home/bernard/Projects/gnuob/gnuob-api/src/main/java -n http://localhost:8080/gnuob-soap/UserWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -b gnuob-group-service-binding.xml -k -p com.netbrasoft.gnuob.api -s /home/bernard/Projects/gnuob/gnuob-api/src/main/java -n http://localhost:8080/gnuob-soap/GroupWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -b gnuob-site-service-binding.xml -k -p com.netbrasoft.gnuob.api -s /home/bernard/Projects/gnuob/gnuob-api/src/main/java -n http://localhost:8080/gnuob-soap/SiteWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -b gnuob-setting-service-binding.xml -k -p com.netbrasoft.gnuob.api -s /home/bernard/Projects/gnuob/gnuob-api/src/main/java -n http://localhost:8080/gnuob-soap/SettingWebServiceImpl?wsdl
rm -Rf output